# BEGIN COPYRIGHT BLOCK
# (C) 2018 Red Hat, Inc.
# All rights reserved.
# END COPYRIGHT BLOCK

services:
  - docker

env:
  - FEDORA=27
  - FEDORA=28

install:
  - docker pull registry.fedoraproject.org/fedora:$FEDORA
  - docker run
      --name=container
      --detach
      -i
      -v $(pwd):/root/ldapjdk
      registry.fedoraproject.org/fedora:$FEDORA
  - docker exec container dnf install -y dnf-plugins-core rpm-build
  - docker exec container dnf copr -y enable @pki/10.6
  - docker exec container dnf builddep -y --spec /root/ldapjdk/ldapjdk.spec
  - docker exec container /root/ldapjdk/build.sh --with-timestamp --with-commit-id rpm

script:
  - docker exec container rpm -Uvh /root/build/ldapjdk/RPMS/*